version: "3"
services:
    nodeapp:
        build: .
        ports:
            - "3000:3000"
    reverseproxy:
        image: nginx:alpine
        volumes: 
        - ./reto-devops.conf:/etc/nginx/conf.d/default.conf
        - ./.privatepass:/etc/nginx/privatepass/.privatepass
        - ./certs:/etc/nginx/certificate
        ports:
            - "443:443"
            - "80:80"

   
    
