apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdep
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp-node
          image: reto-devops_nodeapp
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
